services:
  rccar:
    build:
      context: .
      dockerfile: rccar.Dockerfile
      args:
        ROS_DISTRO: jazzy
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
    depends_on:
      - gamepad
    command: >
      ros2 run rccar correction_total
    restart: unless-stopped

  gamepad:
    build:
      context: .
      dockerfile: gamepad.Dockerfile
      args:
        ROS_DISTRO: jazzy
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - agent
    devices:
      - /dev/input/js0:/dev/input/js0
    command: >
      ros2 run tuw_gamepad gamepad_node --ros-args
      -p use_stamped_velocity:=true 
      -p debug:=true 
      -p lx:=3 
      -p az:=0 
      -p flip_angular_when_reversing:=true 
      -p scale_linear:=-2.0 
      -p scale_angular:=-2.0
    restart: unless-stopped

  agent:
    image: microros/micro-ros-agent:jazzy
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
    environment:
      - ROS_DOMAIN_ID=0
    command: >
      serial --dev /dev/ttyUSB0 -b 3000000
    restart: unless-stopped
