services:
  rccar:
    build:
      context: .
      dockerfile: rccar.Dockerfile
      args:
        ROS_DISTRO: jazzy
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev:/dev
    depends_on:
      - gamepad
    restart: unless-stopped

  gamepad:
    build:
      context: .
      dockerfile: gamepad.Dockerfile
      args:
        ROS_DISTRO: jazzy
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    depends_on:
      - agent
    devices:
      - /dev/input/js0:/dev/input/js0
    restart: unless-stopped

  agent:
    image: microros/micro-ros-agent:jazzy
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - ROS_DOMAIN_ID=0
    command: ["serial", "--dev", "/dev/ttyUSB0", "-b", "921600"]
    restart: unless-stopped

